//! Minimal hand-written `runtime.v1` CRI message types.
//!
//! These mirror the protobuf definitions in
//! `kubernetes/cri-api/pkg/apis/runtime/v1/api.proto`, restricted to the
//! fields Talia needs: listing pod sandboxes and reading one sandbox's
//! status. Field numbers match the upstream `.proto` exactly; unknown fields
//! are skipped on decode, so newer runtimes stay compatible.
//!
//! The types are written by hand (rather than generated by `tonic-build`)
//! so the agent builds without `protoc` at compile time.

use std::collections::HashMap;

/// State of a pod sandbox, mirroring `runtime.v1.PodSandboxState`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, prost::Enumeration)]
#[repr(i32)]
pub enum PodSandboxState {
    /// The sandbox is ready to host containers.
    Ready = 0,
    /// The sandbox is not ready.
    NotReady = 1,
}

/// Network namespace mode, mirroring `runtime.v1.NamespaceMode`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, prost::Enumeration)]
#[repr(i32)]
pub enum NamespaceMode {
    /// The pod's own network namespace, shared by its containers.
    Pod = 0,
    /// Restricted to a single container.
    Container = 1,
    /// The host's network namespace (`hostNetwork: true`).
    Node = 2,
    /// Another container's namespace.
    Target = 3,
}

/// `runtime.v1.ListPodSandboxRequest`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct ListPodSandboxRequest {
    /// Filter selecting which sandboxes to list.
    #[prost(message, optional, tag = "1")]
    pub filter: Option<PodSandboxFilter>,
}

/// `runtime.v1.PodSandboxFilter`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandboxFilter {
    /// Sandbox ID filter (empty = no filtering).
    #[prost(string, tag = "1")]
    pub id: String,
    /// State filter.
    #[prost(message, optional, tag = "2")]
    pub state: Option<PodSandboxStateValue>,
    /// Label selector (unused by Talia).
    #[prost(map = "string, string", tag = "3")]
    pub label_selector: HashMap<String, String>,
}

/// `runtime.v1.PodSandboxStateValue`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandboxStateValue {
    /// The state to filter on.
    #[prost(enumeration = "PodSandboxState", tag = "1")]
    pub state: i32,
}

/// `runtime.v1.ListPodSandboxResponse`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct ListPodSandboxResponse {
    /// The matching pod sandboxes.
    #[prost(message, repeated, tag = "1")]
    pub items: Vec<PodSandbox>,
}

/// `runtime.v1.PodSandbox`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandbox {
    /// Opaque sandbox ID assigned by the runtime.
    #[prost(string, tag = "1")]
    pub id: String,
    /// Pod identity.
    #[prost(message, optional, tag = "2")]
    pub metadata: Option<PodSandboxMetadata>,
    /// Current sandbox state.
    #[prost(enumeration = "PodSandboxState", tag = "3")]
    pub state: i32,
    /// Creation timestamp in nanoseconds.
    #[prost(int64, tag = "4")]
    pub created_at: i64,
    /// Sandbox labels.
    #[prost(map = "string, string", tag = "5")]
    pub labels: HashMap<String, String>,
    /// Sandbox annotations.
    #[prost(map = "string, string", tag = "6")]
    pub annotations: HashMap<String, String>,
    /// Runtime handler name.
    #[prost(string, tag = "7")]
    pub runtime_handler: String,
}

/// `runtime.v1.PodSandboxMetadata`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandboxMetadata {
    /// Pod name, as in the Pod ObjectMeta.
    #[prost(string, tag = "1")]
    pub name: String,
    /// Pod UID, as in the Pod ObjectMeta.
    #[prost(string, tag = "2")]
    pub uid: String,
    /// Pod namespace, as in the Pod ObjectMeta.
    #[prost(string, tag = "3")]
    pub namespace: String,
    /// Sandbox creation attempt number.
    #[prost(uint32, tag = "4")]
    pub attempt: u32,
}

/// `runtime.v1.PodSandboxStatusRequest`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandboxStatusRequest {
    /// ID of the sandbox to inspect.
    #[prost(string, tag = "1")]
    pub pod_sandbox_id: String,
    /// Ask the runtime for extra debug info.
    #[prost(bool, tag = "2")]
    pub verbose: bool,
}

/// `runtime.v1.PodSandboxStatusResponse`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandboxStatusResponse {
    /// The sandbox status.
    #[prost(message, optional, tag = "1")]
    pub status: Option<PodSandboxStatus>,
    /// Runtime-specific extra info (e.g. containerd reports the sandbox PID
    /// under the `"pid"` key).
    #[prost(map = "string, string", tag = "2")]
    pub info: HashMap<String, String>,
}

/// `runtime.v1.PodSandboxStatus`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct PodSandboxStatus {
    /// Opaque sandbox ID assigned by the runtime.
    #[prost(string, tag = "1")]
    pub id: String,
    /// Pod identity.
    #[prost(message, optional, tag = "2")]
    pub metadata: Option<PodSandboxMetadata>,
    /// Current sandbox state.
    #[prost(enumeration = "PodSandboxState", tag = "3")]
    pub state: i32,
    /// Linux-specific sandbox status.
    #[prost(message, optional, tag = "6")]
    pub linux: Option<LinuxPodSandboxStatus>,
}

/// `runtime.v1.LinuxPodSandboxStatus`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct LinuxPodSandboxStatus {
    /// The sandbox's Linux namespaces.
    #[prost(message, optional, tag = "1")]
    pub namespaces: Option<Namespace>,
}

/// `runtime.v1.Namespace`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct Namespace {
    /// Namespace options in effect for the sandbox.
    #[prost(message, optional, tag = "2")]
    pub options: Option<NamespaceOption>,
}

/// `runtime.v1.NamespaceOption`.
#[derive(Clone, PartialEq, prost::Message)]
pub struct NamespaceOption {
    /// Network namespace mode (`NODE` means host networking).
    #[prost(enumeration = "NamespaceMode", tag = "1")]
    pub network: i32,
}

#[cfg(test)]
mod tests {
    use super::ListPodSandboxRequest;
    use super::NamespaceMode;
    use super::PodSandboxFilter;
    use super::PodSandboxState;
    use super::PodSandboxStateValue;
    use prost::Message;

    #[test]
    fn request_roundtrips_through_protobuf() {
        let request = ListPodSandboxRequest {
            filter: Some(PodSandboxFilter {
                id: String::new(),
                state: Some(PodSandboxStateValue {
                    state: PodSandboxState::Ready as i32,
                }),
                label_selector: Default::default(),
            }),
        };

        let mut bytes = Vec::new();
        request.encode(&mut bytes).expect("encoding must succeed");
        let decoded =
            ListPodSandboxRequest::decode(bytes.as_slice()).expect("decoding must succeed");

        assert_eq!(decoded, request);
    }

    #[test]
    fn node_mode_is_two_per_upstream_proto() {
        assert_eq!(NamespaceMode::Node as i32, 2);
        assert_eq!(NamespaceMode::Pod as i32, 0);
    }
}
